// <auto-generated />
using System;
using Beringela.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Beringela.Models.Migrations
{
    [DbContext(typeof(BeringelaDbContext))]
    [Migration("20201106235113_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Beringela.Models.Entities.WeatherForecast", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = "2485397e-5a03-4fab-8df8-526a5b15f7b9",
                            Date = new DateTime(2020, 11, 7, 0, 51, 13, 246, DateTimeKind.Local).AddTicks(810),
                            Summary = "Warm",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = "ede8d5cc-72e0-44c2-adca-cb810f161596",
                            Date = new DateTime(2020, 11, 8, 0, 51, 13, 246, DateTimeKind.Local).AddTicks(4181),
                            Summary = "Balmy",
                            TemperatureC = 21
                        },
                        new
                        {
                            Id = "4e017299-0191-4527-b2f7-1c4134a8412e",
                            Date = new DateTime(2020, 11, 9, 0, 51, 13, 246, DateTimeKind.Local).AddTicks(4315),
                            Summary = "Chilly",
                            TemperatureC = 26
                        },
                        new
                        {
                            Id = "0586bbe0-4ba6-4bec-9ba1-e3834479b7ed",
                            Date = new DateTime(2020, 11, 10, 0, 51, 13, 246, DateTimeKind.Local).AddTicks(4323),
                            Summary = "Chilly",
                            TemperatureC = 13
                        },
                        new
                        {
                            Id = "b36e107a-e474-48b7-9bfa-6762c6f1361b",
                            Date = new DateTime(2020, 11, 11, 0, 51, 13, 246, DateTimeKind.Local).AddTicks(4327),
                            Summary = "Bracing",
                            TemperatureC = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
